# Generated by Django 3.1.3 on 2021-03-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Contact',
        ),
    ]
