# Generated by Django 3.1.3 on 2021-06-10 09:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210307_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('author', models.CharField(max_length=100)),
                ('tags', models.CharField(default='', max_length=500)),
                ('article_body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
