# Generated by Django 3.1.3 on 2021-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
