# Generated by Django 3.1.3 on 2021-06-15 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_articles_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
