# Generated by Django 3.1.3 on 2021-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_articles_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='reading_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
