# Generated by Django 3.1.3 on 2021-08-12 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210809_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_subed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
